# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Building app for tests"
  lane :build do
    gym(scheme: "CI_Example", configuration: "Release", export_method: "development", output_directory: "./build")
  end

  desc "Testing app"
  lane :test do
    scan(
      scheme: "CI_Example",
      clean: true, 
      parallel_testing: false,
      concurrent_workers: 4
    )
  end

  desc "Deploy to TestFlight"
  lane :deploy_testflight do
    latest_tf_build = latest_testflight_build_number(
      app_identifier: "com.yourcompany.yourapp",
      api_key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"]
    )

    increment_build_number_in_xcodeproj(
      build_number: latest_tf_build + 1
    )

    build

    pilot(
      app_identifier: "com.yourcompany.yourapp",
      api_key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      skip_waiting_for_build_processing: true,
    )
  end
end
